routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['adminAuth']], function () {
	Route::get('/','AdminController@dashboard')->name('admin.dashboard');
	Route::get('/user/toggle-status/{id}','Admin\UserController@toggleStatus')->name('admin.user.toggleStatus');
	Route::resource('user','Admin\UserController');
	Route::get('logout','AdminController@logout')->name('admin.logout');
        Route::resource('role','Admin\RoleController');
        Route::resource('course','Admin\CourseController');
        Route::get('role/{id}/permissions','Admin\RoleController@rolePermissions')->name('role.permissions');


});

Route::get('/login','AdminController@loginView')->name('admin.login');
Route::post('login','AdminController@login')->name('admin.login.post');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('home');});

Route::post('/signup', ['uses' => 'UserController@signUp','as' => 'signup']);
Route::post('/signin', ['uses' => 'UserController@signIn','as' => 'signin']);
Route::get('/logout', ['uses' => 'UserController@Logout','as' => 'logout']);

Route::get('/login/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Permission;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Role extends BaseModel
{
    use SoftDeletes;

    protected $appends = ['encrypted_id'];
    
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;
use App\Models\Role;
use App\Models\RolePermission;
use Illuminate\Database\Eloquent\Collection;



class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
         if($request->ajax()){
            $results = Role::all();
            return DataTables::of($results)
                ->addColumn('action', 'admin.roles.datatables_actions')
                ->make(TRUE);
         }
        return view('admin.roles.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    
    public function rolePermissions(Request $request,$id){
        $roleId = decryptId($id);
        $role = Role::find($roleId);
        if($request->ajax()){
            $results = RolePermission::where('role_id', $roleId)->with('role','permission');
            return DataTables::of($results)
                ->addColumn('action', 'admin.roles.permission_datatables_actions')
                ->make(TRUE);
        }
        return view('admin.roles.permission')->with('role', $role);
    }
}

resources/views/admin/roles/datatables_actions.blade.php
{!! Form::open(['route' => ['role.destroy', $encrypted_id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('role.permissions', $encrypted_id) }}">View Permissions</a>
</div>
{!! Form::close() !!}

resources/views/admin/roles/index.blade.php
@extends('admin.layout.main')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Roles</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right"  style="margin-top: -10px;margin-bottom: 5px" href="{!! route('role.create') !!}">Add Role</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.roles.table')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/permission.blade.php
@extends('admin.layout.main')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Permissions:: {!! $role->name !!}</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right"  style="margin-top: -10px;margin-bottom: 5px" href="#">Add Permission</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.roles.permission_table')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/permission_datatables_actions.blade.php
<div class='btn-group'>
    <a href="" class='btn btn-danger btn-xs'>
        <i class="glyphicon glyphicon-trash"></i>
    </a>
</div>

resources/views/admin/roles/permission_table.blade.php
<table id="role" class="table table-condensed">
    <thead>
        <tr>
            <th>Permission</th>
            <th>Description</th> 
            <th>Action</th>
        </tr>
    </thead>
</table>

@section('scripts')
  
    <script>
        $(function () {
            $('#role').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                autoWidth: false,
                ajax: '{{ route('role.permissions',$role->encryptedId) }}',
                order: [[ 0, "desc" ]],
                aoColumns: [
                    {"data":"permission.name","name":"permission.name"},
                    {"data":"permission.description","name":"permission.description"},
                    {"data":"action","name":"action", searchable: false, orderable: false}
                ]
            });
        });
    </script>
@endsection

resources/views/admin/roles/role_permission.blade.php
@extends('admin.layout.main')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Permissions</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right"  style="margin-top: -10px;margin-bottom: 5px" href="{!! route('role.create') !!}">Add Permission</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                  
                
        @foreach ($data as $row) 
           
        <p>{{ $row->permission->id }}</p>
        <p>{{ $row->permission->name }}</p>
         
           
        @endforeach
                
               
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/table.blade.php
<table id="role" class="table table-condensed">
    <thead>
        <tr>
            <th>Role</th>
            <th>Description</th> 
            <th>Action</th>
        </tr>
    </thead>
</table>

@section('scripts')
  
    <script>
        $(function () {
            $('#role').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                autoWidth: false,
                ajax: '{{ url("admin/role") }}',
                order: [[ 0, "desc" ]],
                aoColumns: [
                    {"data":"name","name":"name"},
                    {"data":"description","name":"description"},
                    {"data":"action","name":"action", seachable: false, orderable: false}
                ]
            });
        });
    </script>
@endsection