routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['adminAuth']], function () {
	Route::get('/','AdminController@dashboard')->name('admin.dashboard');
	Route::get('/user/toggle-status/{id}','Admin\UserController@toggleStatus')->name('admin.user.toggleStatus');
	Route::resource('user','Admin\UserController');
	Route::get('logout','AdminController@logout')->name('admin.logout');
        Route::resource('role','Admin\RoleController');
        Route::resource('course','Admin\CourseController');
        Route::get('role/{id}/permissions','Admin\RoleController@rolePermissions')->name('role.permissions');


});

Route::get('/login','AdminController@loginView')->name('admin.login');
Route::post('login','AdminController@login')->name('admin.login.post');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('home');});

Route::post('/signup', ['uses' => 'UserController@signUp','as' => 'signup']);
Route::post('/signin', ['uses' => 'UserController@signIn','as' => 'signin']);
Route::get('/logout', ['uses' => 'UserController@Logout','as' => 'logout']);

Route::get('/login/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

app/Models/User.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
class User extends Authenticatable
{
    use SoftDeletes;

    protected $appends = ['role_name','encrypted_id'];

    const ROLE_SUPER_ADMIN = 1;
    const ROLE_ADMIN = 2;
    const ROLE_PRIMARY_UNIVERSITY = 3;
    const ROLE_SECONDARY_UNIVERISTY = 4;
    const ROLE_INSTRUCTOR = 5;
    const ROLE_STUDENT = 6;

    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;

    public function getAttribute($key){
        if (array_key_exists($key, $this->relations)|| method_exists($this, $key)) {
            return parent::getAttribute($key);
        }
        else {
            return parent::getAttribute(snake_case($key));
        }
    }

    public function setAttribute($key, $value){
        return parent::setAttribute(snake_case($key), $value);
    }

    public function getEncryptedIdAttribute(){
        return encryptId($this->id);
    }

    public function userRole(){
        return $this->belongsTo(Role::class,'role','id');
    }

    /**
     * @return string
     */
    public function getRoleNameAttribute(){
        switch($this->role){
            case self::ROLE_SUPER_ADMIN:
                return "Super Admin";
                break;
            case self::ROLE_ADMIN:
                return "Admin";
                break;
            case self::ROLE_PRIMARY_UNIVERSITY:
                return "Primary University";
                break;
            case self::ROLE_SECONDARY_UNIVERISTY:
                return "Secondary University";
                break;
            case self::ROLE_INSTRUCTOR:
                return "Instructor";
                break;
            case self::ROLE_STUDENT:
                return "Student";
                break;
             default:
                return "NA";
        }
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Yajra\DataTables\DataTables;
use App\Http\Requests\Admin\User\CreateUserRequest;
use App\Providers\Admin\UserServiceProvider;
use Laracasts\Flash\Flash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()){
            $results = User::all();

            return DataTables::of($results)
                ->editColumn('status', function($result){
                    $status = 'Inactive';
                    if($result->status == User::STATUS_ACTIVE) {
                        $status = 'Active';
                    }
                    return $status;
                })
                ->addColumn('action', 'admin.users.datatables_actions')
                ->make(TRUE);
        }
        return view('admin.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request){
        $res = UserServiceProvider::createUser($request->all());
        if($res){
            Flash::success('User created successfully');
            return redirect(route('user.index'));
        }else{
            Flash::error('Something went wrong. Please try again later.');
            return redirect(route('user.index'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id){
       echo decryptId($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id){
        $userId = decryptId($id);
        $user = User::find($userId);
        if(empty($user)){
            Flash::error('User not available');
            return redirect(route('user.index'));
        }
        return view('admin.users.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $userId = decryptId($id);
        $user = User::find($userId);
        if(empty($user)){
            Flash::error('User not available');
            return redirect(route('user.index'));
        }
        $user->name = $request->name;
        $user->role = $request->role;
        $res = $user->save();
        if($res){
            Flash::success('User updated successfully');
        }else{
            Flash::error('Oops! Something went wrong. Please try again later.');
        }
        return redirect(route('user.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $userId = decryptId($id);
        $user = User::find($userId);
        if(empty($user)){
            Flash::error('User not available');
            return redirect(route('user.index'));
        }
        $res = $user->delete();
        if($res){
            Flash::success('User deleted successfully');
        }else{
            Flash::error('Oops! Something went wrong. Please try again later.');
        }
        return redirect(route('user.index'));
    }

    public function toggleStatus($id){
        $userId = decryptId($id);
        $user = User::find($userId);
        if(empty($user)){
            Flash::error('User not available');
            return redirect(route('user.index'));
        }
        if($user->status == User::STATUS_ACTIVE){
            $user->status = User::STATUS_INACTIVE;
        }else{
            $user->status = User::STATUS_INACTIVE;
        }
        $res = $user->save();
        if($res){
            Flash::success('User\'s status updated successfully');
        }else{
            Flash::error('Oops! Something went wrong. Please try again later.');
        }
        return redirect(route('user.index'));
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Providers\Admin\UserServiceProvider;
use App\Http\Requests\Admin\LoginRequest;
use App\Http\Requests\Admin\RegisterRequest;
use App\Models\User;
use DB;


class UserController extends Controller
{
    private $date ;
    public function signUp(RegisterRequest $request){
		UserServiceProvider::register($request->all());
		return redirect(route('admin.dashboard'));      

    }
    
    public function logOut(){
        Auth::logout();
		return redirect(url('/'));

    }
	
    public function signIn(LoginRequest $request)
    {
        $this->date = date('Y-m-d H:i:s');
        if (Auth::attempt(['email' => $request['email'],'password' => $request['password'],'status'=>User::STATUS_ACTIVE])) {
            $user = User::where('email', $request['email'])->first();
            $user->lastLogin = $this->date;
            $user->save();
                    
            return redirect(route('admin.dashboard'));
        }
        return redirect()->back()->with(['message' => trans('messages.common.invalid_credential')]);
    }
	
}

resources/views/admin/users/create.blade.php
@extends('admin.layout.main')

@section('content')
    <section class="content-header">
        <h1>
            Users
        </h1>
    </section>
    <div class="content">
        @include('admin.layout.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'user.store']) !!}

                        @include('admin.users.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/datatables_actions.blade.php
{!! Form::open(['route' => ['user.destroy', $encrypted_id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ url('admin/user', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('user.edit', $encrypted_id) }}" class='btn btn-info btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>

    @if($status == \App\Models\User::STATUS_ACTIVE)
        <a href="{{ route('admin.user.toggleStatus', $encrypted_id) }}" class='btn btn-success btn-xs'>
            <i class="glyphicon glyphicon-ok-circle"></i>
        </a>
    @else
        <a href="{{ route('admin.user.toggleStatus', $encrypted_id) }}" class='btn btn-danger btn-xs'>
            <i class="glyphicon glyphicon-ban-circle"></i>
        </a>

    @endif
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure that you want to delete user?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/admin/users/edit.blade.php
@extends('admin.layout.main')

@section('content')
    <section class="content-header">
        <h1>
            Users
        </h1>
   </section>
   <div class="content">
       @include('admin.layout.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($user, ['route' => ['user.update', $user->encrypted_id], 'method' => 'patch']) !!}

                        @include('admin.users.edit_fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/users/edit_fields.blade.php
<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control','readonly'=>true]) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Role Field -->
<div class="form-group col-sm-6">
    {!! Form::label('role', 'Role:') !!}
    {!! Form::select('role', array('Select Role','Super Admin','Admin','Primary University','Secondary University','Instructor','Student'),null, ['class' => 'form-control select2']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! url('admin/user') !!}" class="btn btn-default">Cancel</a>
</div>


@section('scripts')
<script>
    $(function () {
         $('.select2').select2();

         $AUTOCOMPLETE_JS$


    });
</script>
@endsection

resources/views/admin/users/fields.blade.php
<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Role Field -->
<div class="form-group col-sm-6">
    {!! Form::label('role', 'Role:') !!}
    {!! Form::select('role', array('Select Role','Super Admin','Admin','Primary University','Secondary University','Instructor','Student'),null, ['class' => 'form-control select2']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! url('admin/user') !!}" class="btn btn-default">Cancel</a>
</div>


@section('scripts')
<script>
    $(function () {
         $('.select2').select2();

         $AUTOCOMPLETE_JS$


    });
</script>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layout.main')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Users</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right"  style="margin-top: -10px;margin-bottom: 5px" href="{!! route('user.create') !!}">Add User</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.users.table')
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/show.blade.php
@extends('admin.layout.main')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Users</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right" target="_blank" style="margin-top: -10px;margin-bottom: 5px" href="{!! url('admin/users/export-post/'.$users->id) !!}">Export Related Post</a>
        </h1>
    </section>
<div class="content" style="margin-top: 20px">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('admin.users.show_fields')
                    <a href="{!! url('admin/users') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/show_fields.blade.php
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $users->name !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $users->email !!}</p>
</div>

<!-- Password Field -->
<div class="form-group">
    {!! Form::label('username', 'Username:') !!}
    <p>{!! $users->username !!}</p>
</div>

<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>
        @if($users->is_active == \App\Models\User::STATUS_ACTIVE)
            Active
        @else
            Inactive
        @endif    
    </p>
</div>

resources/views/admin/users/table.blade.php
<table id="users" class="table table-condensed">
    <thead>
        <tr>
            <th>Email</th>
            <th>Name</th>
            <th>Role</th>
            <th>Status</th>  
            <th>Action</th>
        </tr>
    </thead>
</table>

@section('scripts')
  
    <script>
        $(function () {
            $('#users').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                autoWidth: false,
                ajax: '{{ url("admin/user") }}',
                order: [[ 0, "desc" ]],
                aoColumns: [
                    {"data":"email","name":"email"},
                    {"data":"name","name":"name"},
                    {"data":"role_name","name":"role_name"},
                    {"data":"status","name":"status"},
                    {"data":"action","name":"action", seachable: false, orderable: false}
                ]
            });
        });
    </script>
@endsection