routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['adminAuth']], function () {
	Route::get('/','AdminController@dashboard')->name('admin.dashboard');
	Route::get('/user/toggle-status/{id}','Admin\UserController@toggleStatus')->name('admin.user.toggleStatus');
	Route::resource('user','Admin\UserController');
	Route::get('logout','AdminController@logout')->name('admin.logout');
        Route::resource('role','Admin\RoleController');
        Route::resource('course','Admin\CourseController');
        Route::get('role/{id}/permissions','Admin\RoleController@rolePermissions')->name('role.permissions');


});

Route::get('/login','AdminController@loginView')->name('admin.login');
Route::post('login','AdminController@login')->name('admin.login.post');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {return view('home');});

Route::post('/signup', ['uses' => 'UserController@signUp','as' => 'signup']);
Route::post('/signin', ['uses' => 'UserController@signIn','as' => 'signin']);
Route::get('/logout', ['uses' => 'UserController@Logout','as' => 'logout']);

Route::get('/login/{social}','Auth\LoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
Route::get('/login/{social}/callback','Auth\LoginController@handleProviderCallback')->where('social','twitter|facebook|linkedin|google|github|bitbucket');

resources/views/admin/courses/create.blade.php
@extends('admin.layout.main')

@section('content')
    <section class="content-header">
        <h1>
            Courses
        </h1>
    </section>
    <div class="content">
        @include('admin.layout.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'course.store']) !!}

                        @include('admin.courses.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/courses/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Course Title:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Role Field -->
<div class="form-group col-sm-6">
    {!! Form::label('category', 'Course Category:') !!}
    {!! Form::select('category', array('Select Category','Business','Finance','Photography','Technology'),null, ['class' => 'form-control select2']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! url('admin/user') !!}" class="btn btn-default">Cancel</a>
</div>


@section('scripts')
<script>
    $(function () {
         $('.select2').select2();

         $AUTOCOMPLETE_JS$


    });
</script>
@endsection

resources/views/admin/courses/index.blade.php
@extends('admin.layout.main')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Courses</h1>
        <h1 class="pull-right">
            <a class="btn btn-primary pull-right"  style="margin-top: -10px;margin-bottom: 5px" href="{!! route('course.create') !!}">Add Course</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                   
                No Course Available !!
                
            </div>
        </div>
    </div>
@endsection